"""empty message

Revision ID: 1946b47dc51d
Revises: 764235d6ca32
Create Date: 2024-07-23 16:04:33.809083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1946b47dc51d'
down_revision = '764235d6ca32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precio_tickets', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precio_tickets', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
