"""empty message

Revision ID: 764235d6ca32
Revises: 90db6051a51f
Create Date: 2024-07-23 15:28:16.569543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764235d6ca32'
down_revision = '90db6051a51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
